# Generated by Django 4.1.7 on 2023-03-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_alter_turnos_disponible_alter_turnos_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=300)),
                ('telefono', models.IntegerField()),
                ('mensaje', models.CharField(max_length=300)),
            ],
        ),
    ]
